### ISSUE TITLE
add changelog and tagged versions

### ISSUE THREAD

**Issue by kmindi** [latextemplates/scientific-thesis-cover#15]
For the movement to ctan publications we should add a changelog file with the versions and use git tags to create specific versions that match the ctan publications.

**Comment by koppor** [comment]
Sure!

http://keepachangelog.com/en/1.0.0/

I already did it for the scientific-thesis-template


Am 19.12.2017 11:09 schrieb "Kai Mindermann M.Sc." <notifications@github.com

**Comment by koppor** [comment]
Initial CHANGELOG added: https://github.com/latextemplates/scientific-thesis-cover/blob/master/CHANGELOG.md

Do we need a release howto or is it "common sense" to add tags and a CHANGELOG entry for each release?

I currently opt for "common sense" and, due to the lack of man power, I want to keep the number of open issues small. Thus, I close the issue.
